[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
runOnSave = true
enableWebsocketCompression = true
port = 8501
# showErrorDetails = false  # ❌ Deprecated
# viewSource = false        # ❌ Deprecated


[logger]
level = "info"
