[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
showErrorDetails = false
enableCORS = false
enableXsrfProtection = false
headless = true
runOnSave = true
enableWebsocketCompression = true
port = 8501
viewSource = false  #  This hides the “View Source” button
